name: Build

on: [push, pull_request_target, workflow_dispatch]

jobs:

  build-windows:
    runs-on: 'windows-latest'

    strategy:
      matrix:
        platform: ['windows']
        arch: ['x64']
        buildmode: ['release']
        toolset: ['14.11']

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        run: .github/scripts/compile.bat ${{ matrix.platform }}${{ matrix.arch }} ${{ matrix.buildmode }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary
          path: build\*.exe
